# Generated by Django 5.2.5 on 2025-08-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='marca',
            field=models.CharField(blank=True, help_text='Marca do produto. Ex: Ninho', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade_em_estoque',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade_minima',
            field=models.DecimalField(decimal_places=3, default=5, max_digits=10, verbose_name='Quantidade Mínima de Alerta'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tamanho',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Tamanho ou volume. Ex: 0.400 para 400g, 1.5 para 1.5L', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade_medida',
            field=models.CharField(choices=[('un', 'Unidade'), ('kg', 'Quilograma'), ('g', 'Grama'), ('L', 'Litro'), ('ml', 'Mililitro'), ('pacote', 'Pacote'), ('caixa', 'Caixa'), ('lata', 'Lata'), ('fardo', 'Fardo')], default='un', max_length=10),
        ),
    ]
